language: node_js
node_js:
- '6.10'
cache:
  directories:
    - node_modules

script:
    - npm install
    - npm test
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run test:e2e:deploy; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run test:e2e:remove; fi'

after_script: nyc report --reporter=text-lcov | coveralls
