service:
  name: realworld-api-spec

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    AUTH_TABLE: dynamo-table-${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.AUTH_TABLE}"

package:
  excludeDevDependencies: true

functions:
  del:
    handler: src/auth/handler.del
    environment:
      AUTH_TABLE_NAME: ${self:provider.environment.AUTH_TABLE}
      AUTH_TABLE_ADD_TIMESTAMPS: TRUE
    events:
      - http:
          method: delete
          path: api/users/{email}
          cors: true
  register:
    handler: src/auth/handler.register
    environment:
      AUTH_TABLE_NAME: ${self:provider.environment.AUTH_TABLE}
      AUTH_TABLE_ADD_TIMESTAMPS: TRUE
    events:
      - http:
          method: post
          path: api/users
          cors: true

resources:
  Resources:
    AuthTable:
      Type: AWS::DynamoDB::Table
      # NOTE: If you are testing and have deletion policy on during a serverless remove, you must manually delete the table before re-deploying.
      # DeletionPolicy: Retain # Keeps around the DynamoDB resource when we redeploy/destroy
      Properties:
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: createTime
            AttributeType: N
        KeySchema:
          - AttributeName: email
            KeyType: HASH
          - AttributeName: createTime
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.AUTH_TABLE}
